### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by tasteeins** [fiso64/slsk-batchdl#1]

**Comment by tasteeins** [comment]
Hi Fiso
First of all thank you so much for taking on this issue! you will make my life so much more nice!

Then i want to say that i completely dont know about git hub etc. and am a pretty noob in all programming areas.
Through the research about your app i already learned a lot new!

Still - i dont know how to make your programm run after i downloaded the repository. i cant find any exe etc. 

Maybe you could do another kind task and write a little super beginners how to on how to make SLSK-BATCHDL work because i´d ABSOLUTELY LOVE to use it :)

In eternal gratefullnes
tasteeins

**Comment by l3rockstar** [comment]
Hi tasteeins, depending on what OS you are using there are different ways to get the .exe file that you will need to use to run this. I would recommend running it in Visual Studio (for whatever OS you use), then build the slsk-batchdl.csproj file and it should generate the executable for you to actually use this project. Fair warning though, I would recommend looking at some simpler (such as hello world) project files before you try and get this to run as I am a software engineer with minimal coding expert and while I made it through, it is not the easiest thing to just slide into and use as is, there is no UI or easy way to go about it.

**Comment by brusfest** [comment]
1. Install Visual Studio Community Edition
2. File > Open project > slsk-batchdl-.sln
3. Tools > NuGet Package Manager > Manage NuGet Packages for Solution
4. Double check under the install tab that packages are installed. If it's not, and you're only package source is "Microsoft Visual Studio Offline Packages follow step 5 & 6.
5. Tools > NuGet Package Manager > Package Manager Settings, then click "Package Sources".
6. Click the + icon and add nuget.org as "Name" and https://api.nuget.org/v3/index.json as "Source".
7. Click the Run button (probably says "slsk-batchdl" by it)
8. You're slsk-batchdl.exe is now under bin/Debug/net6.0
9. If you have this folder open in File Explorer press Ctrl + L > type cmd > Enter
10. Type e.g. "slsk-batchdl --user random123 --pass password123 --spotify spotify.com/your-playlist --path C:\Users\Music

If I remember correctly SoulSeek doesn't have registration, but for some reason has username and passord. So you can pretty much type in anything.
