### ISSUE TITLE
"The server connection must be connected and logged in to perform a search (currently: Disconnected)"

### ISSUE THREAD

**Issue by crazyserb** [fiso64/slsk-batchdl#12]
I am using the app with the following .conf parameters (using CSV list as a source):

-s 
--skip-mode "name" 
--pref-format "mp3" 
--format "mp3,wav,flac" 
--min-bitrate "256" 
--max-bitrate "320" 
--skip-not-found 
--remove-ft  
--search-timeout 6000 
--max-stale-time 30000 
--display "simple" 
--concurrent-downloads 4

and somehow, no matter what I do, or change in this config, I get this error messages printed over and over within 2-3 minutes of this running:

"The server connection must be connected and logged in to perform a search (currently: Disconnected)"

What am I missing?

Are some of the parameters too aggressive and SLSK just keeps booting this app out? 

Or is there an issue with the latest release (1.5.1) that might need to be addressed?

**Comment by fiso64** [comment]
Doesn't happen for me. 
I can make it reconnect automatically, although I would like to first find out why it's disconnecting. You're not trying to use soulseek somewhere else while it's running?

**Comment by crazyserb** [comment]
I don't know. Is there some sort of logging option/flag we can turn on, to create a debug log in the background to save these errors, exceptions, etc, so you can figure out why it's disconnecting?

And no, I don't have Soulseek running anywhere else. I figured being logged into multiple instances of it would trigger some red flags over there or something already...

**Comment by fiso64** [comment]
Never mind, I can reproduce it. I don't know what causes it though. Try --concurrent-downloads 2 or 1 for now

**Comment by crazyserb** [comment]
Interesting... ok, I'll get on testing that version now. Thanks for a quick fix/resolution.
