### ISSUE TITLE
The handle is invalid. at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)

### ISSUE THREAD

**Issue by vicentemont** [fiso64/slsk-batchdl#13]
Im getting this error when trying to download tracks

**Comment by vicentemont** [comment]
Got it! I was not using default CMD

**Comment by vicentemont** [comment]
"O identificador é inválido" is in portuguese but it translates to "The handle is invalid"

**Comment by vicentemont** [comment]
Also a good thing you could do is to auto select another port if listening port 50000 isn't available as this appears to be the default port on recordbox. if i have rekordbox open i always get that error..

**Comment by fiso64** [comment]
> Also a good thing you could do is to auto select another port if listening port 50000 isn't available as this appears to be the default port on recordbox. if i have rekordbox open i always get that error..

I guess having an open port sometimes helps to get more results? Otherwise I could just disable listening altogether.

**Comment by fiso64** [comment]
the invalid handle error seems to originate from the [progress bar library](https://github.com/goblinfactory/progress-bar/) I use. It's not pretty, but you can use `--display simple` if you want it to work in git bash.
