### ISSUE TITLE
feat: Support subfolders in --name-format

### ISSUE THREAD

**Issue by andrewjmetzger** [fiso64/slsk-batchdl#16]
Hello! 

I would like to request support for subfolders in the `--name-format` option. In v1.6.1, the downloaded files are all placed in a single folder. This enhancement would allow the use of `/` to specify subfolders for keeping downloads organized.

As an example, consider the name format `{artist}/{artist} - {title}`. This could generate a file structure like

```
downloads/
  The Beatles/
    The Beatles - Come Together.flac
  Phil Collins/
    Phil Collins - In the Air Tonight.flac
```

Instead of 

```
downloads/
  The Beatles - Come Together.flac
  Phil Collins - In the Air Tonight.flac
```

Thank you for making slsk-batchdl. It's been super helpful to fill out the gaps in my library. :)

**Comment by fiso64** [comment]
I updated 1.6.1 https://github.com/fiso64/slsk-batchdl/releases/tag/v1.6.1

**Comment by andrewjmetzger** [comment]
I ran this for a few hours to test -- the new V1.6.1 build works well, thanks!
Time to do the rest now... 😉 

PS: Happy new year!
