### ISSUE TITLE
Is it possible to search and download by "album=X, artist=X" only? Not using "title=X"

### ISSUE THREAD

**Issue by buzzytrent90** [fiso64/slsk-batchdl#17]
I would like search and download by "album". Is this possible?

I cannot find a way of searching manually or using CSV by just using the input of "artist" & "album". It seems the program errors if no "title" is given. Is this because soulseek list single files? having to include a "title" in a search for an album will not work.
Is it possible to search by name of "directory" by the uploader. Therefore you could search for an album by searching for the album name as a directory name,

**Comment by fiso64** [comment]
I have added album downloading in the newest version, let me know how it goes if you decide to use it

**Comment by renaudjx** [comment]
To download albums from a CSV file you can still create a python script to loop on each row and execute the command.

My Python script :
```Python
import csv
import subprocess

# Path to the CSV file
csv_file_path = '/path/to/your/file.csv'

# Command template
command_template = 'slsk-batchdl "album={album},artist={artist}"'

# Read the CSV file
with open(csv_file_path, newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        # Replace placeholders with actual data from the CSV
        command = command_template.format(album=row['Album'], artist=row['Artist'])
        
        # Execute the command
        subprocess.run(command, shell=True)
```

**Comment by fiso64** [comment]
I have added the ability to download albums from a csv file https://github.com/fiso64/slsk-batchdl/releases/tag/v2.1
