### ISSUE TITLE
crashes immediately

### ISSUE THREAD

**Issue by Scurn** [fiso64/slsk-batchdl#18]
i have downloaded in the past and have had no issues. now, whenever I run it, no matter which version or release or how many times I restart, it loads for half a second and then the terminal closes. I can even see the text for a split second when the window opens so I don't know whats going on

**Comment by fiso64** [comment]
The default behavior on windows is to close the terminal window when the program exits. Start cmd separately and then execute the program from there to see the error.

**Comment by Head2k3k** [comment]
For anyone not familiar with cmd at all, use "pause" command in the end for it to not close.
