### ISSUE TITLE
Unhandled exception. System.Exception: Unknown argument: --listen-port    at Program.Main(String[] args)    at Program.<Main>(String[] args)

### ISSUE THREAD

**Issue by tasteeins** [fiso64/slsk-batchdl#19]
im trying to use a different port but it doesnt seem to recognise the input...

C:\Users\slsk-batchdl.exe --username xx --password xx --spotify https://open.spotify.com/playlist/ --path C:\Users --pref-format flac --skip-existing --concurrent-processes 4 --reverse --listen-port XXXXX

**Comment by fiso64** [comment]
`concurrent-processes` has been renamed to `concurrent-downloads`
