### ISSUE TITLE
Suggestion: Add option to remove successful files from Spotify playlist

### ISSUE THREAD

**Issue by teubenja** [fiso64/slsk-batchdl#2]
Hey! Love the program, it works really well 😄 

I would love to have an option to clear successful files from Spotify playlists. I use a sort of download queue playlist, and it would be nice to not have it be cluttered with already downloaded songs. I know that the duplicate check exists, but not having them there in the first place saves on processing. Furthermore, by only deleting the successful files I can easily see which ones I either need to retry or find somewhere else.

I'm looking forward to your reaction, and again thank you for your work!

**Comment by teubenja** [comment]
By the way, if you like the idea I can also have a look myself if I can come up with some code :)

**Comment by fiso64** [comment]
I added `--remove-from-playlist` in the newest release. Does it work?

**Comment by teubenja** [comment]
It works, yes! It does open the Spotify OAUTH page every time you download now, even though I already gave the permission. And it does not remove songs for files that already exist in the output/music folders, which was not requested but I thought I'd mention it nonetheless.

**Comment by fiso64** [comment]
@teubenja The OAUTH page has always appeared whenever an actual login was needed (i.e when downloading private playlists). I'm sure there is a cleaner way of doing this.

**Comment by teubenja** [comment]
For me it only appeared the first time, then I could download multiple lists without it bringing the page up. And the page that I see now is only the confirmation page, I don't need to re-login
