### ISSUE TITLE
Keep getting "Failed to download: <songname>"

### ISSUE THREAD

**Issue by alexnbferreira** [fiso64/slsk-batchdl#20]
Hi there

I've been trying to make this work for some time and I'm currently stuck in this issue with no way to make it work.
I am supplying a program with a spotify playlist. It starts going through the song and as when trying to download the first one I get 
`"Failed to download : <songname> , skipping". `
It skips to the second song, and then prints 
`"Out of download retries: <songname>, skipping"`

I have tried printing the results and can confirm the program is finding lots of options to download for each song. 
I have tried using random logins and my own.
I have tried many of the different flags and options to see if anything would let me download but to not success. 
![image](https://github.com/fiso64/slsk-batchdl/assets/11177119/418064c8-61c0-4fd6-875a-1b59d386a64d)

I have used both SoulseekQT and Nicotine+ with no problem. 

If you could help me figure out what's missing here I would appreciate it a lot 👍 
Thanks

**Comment by fiso64** [comment]
I have updated the latest 1.6.1 version with the fix
