### ISSUE TITLE
Trojan:Script/Wacatac.B!ml in 1.6

### ISSUE THREAD

**Issue by gertgert121** [fiso64/slsk-batchdl#21]
Hi, don't know if this is an error or false positive but when trying to DL the most recent release (1.6 I believe), I was getting flagged with the file containing this Trojan.

**Comment by fiso64** [comment]
You can check virustotal to see that it's a false positive from your retarded scanner. Can you tell me which program is flagging it?

**Comment by gertgert121** [comment]
Windows Defender is flagging it. Just wanted to let you know

**Comment by fiso64** [comment]
Thanks. Seems like defender has a false positive problem as I can see quite a few complaints from devs whose own software got flagged by it. I could submit the file for ["malware analysis"](https://www.microsoft.com/en-us/wdsi/filesubmission?) but this seems like an arduous process that I would have to redo for every new version. In any case it's no big deal as the program can be easily compiled from source in case you're not convinced by virustotal.

**Comment by gertgert121** [comment]
Already compiled it :) just wanted to make a post in case others had
similar issues/worries going forward. Thanks for all your work/help!
