### ISSUE TITLE
straight commands like --format --min-bitrate etc. seem not to work

### ISSUE THREAD

**Issue by tasteeins** [fiso64/slsk-batchdl#22]
With those Commands i always get this error codes:
Unhandled exception. System.Exception: Unknown argument: --format
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)
   
My Command looks like this for example:
C:\Users\XXX\slsk-batchdl.exe --username XX --password XY --spotify https://open.spotify.com/playlist/XXX --path C:\Users\XX --format flac,wav --skip-existing --desperate

It would be GREAT if i could solve that.... but i cant

**Comment by fiso64** [comment]
Can't reproduce, you probably forgot to put quotation marks around one of your arguments. Also this is the 5th time you're opening an issue because you can't use the command line. Come on.

**Comment by tasteeins** [comment]
Im realy trying and hope to find help here and to progress from that. So thank you a lot for taking the time to answer even though i dont understand why its working wit --pref-format flac,wav opposed to --format flac,wav

Really dont want to annoy and just trying to understand
kind regards in total humbleness
