### ISSUE TITLE
"running" but not doing anything. No Errors

### ISSUE THREAD

**Issue by varoudis** [fiso64/slsk-batchdl#24]
I get no error or anything. Any ideas for how to troubleshoot?

```.\slsk-batchdl.exe --username "kekeke" --password "kekeke" --pref-format "flac" --concurrent-downloads 6 -p .\ .\artist_and_track_names.csv

Windows: Recommended to use the command prompt instead of terminal app to avoid printing issues.

Parsing CSV track info

Using inferred columns: artist:"Artist", title:"Title".

Warning: No duration column found, results may be imprecise

  XXX - XXX

  XXXX - XXXXX

  ... (etc)

Downloading 10 tracks```

Then it stays there and does nothing.
Windows 11 Pro.

**Comment by fiso64** [comment]
Try running it with input "artist=Artist,title=Title" with some valid Artist and Title. Does it work?
Please provide the full command you used and a section of the csv file so I can try to reproduce it.

**Comment by fiso64** [comment]
I'm unable to reproduce it for the single track download (obviously). Could you try the self-contained version? And if you have wsl, could you try the linux build?

I will add an option to print debug info.

**Comment by fiso64** [comment]
I have updated the latest 2.0 release to add the `--debug` option. Please try running the single song search with the following additional options: `--debug --display simple --concurrent-downloads 1`

**Comment by varoudis** [comment]
It stops on "Login XXXX". The login/pass works. I tested on the same system with the official GUI
Any ideas?

**Comment by fiso64** [comment]
I have updated the latest release again to add the option `--no-wait-for-internet`. Please run it again with the options above + `--no-wait-for-internet`. If it then gets stuck at "Setting share count", try again with the additional option `--no-modify-share-count`.

**Comment by varoudis** [comment]
"--no-wait-for-internet" Worked.
What was this doing?

**Comment by fiso64** [comment]
Thank you for debugging. The internet check is useful to prevent the program from failing after a short network disconnect, but I realize now that it would be smarter to just catch that particular error than checking with google..
