### ISSUE TITLE
--min-bitrate seems not to work

### ISSUE THREAD

**Issue by poeti8** [fiso64/slsk-batchdl#27]
When I write `--format flac --min-bitrate 2000 --max-bitrate 5000` I still get files downloaded with bitrates around 900.

**Comment by fiso64** [comment]
The file bitrate may be unavailable depending on the client used by the peer (I think the default soulseek client does not share the file bitrate, while nicotine+ does). slsk-batchdl skips the bitrate check if the bitrate is unavailable, this is probably why you are getting lower bitrate files. 

I'll add an option to make it strict, but remember that setting a min-bitrate with that option will make it automatically ignore all downloads from peers who are using the default soulseek client.

**Comment by fiso64** [comment]
Try the new version https://github.com/fiso64/slsk-batchdl/releases/tag/v2.0.1 with `--strict`

**Comment by poeti8** [comment]
Thanks. Would there be a way to maybe filter based on the attributes? 

![image](https://github.com/fiso64/slsk-batchdl/assets/23660003/0db963a4-8295-470e-ad3f-8d567f7c1376)

**Comment by fiso64** [comment]
There is already `--max-samplerate`. Do you want to filter based on min sample rate or bit depth?

**Comment by poeti8** [comment]
>There is already --max-samplerate. Do you want to filter based on min sample rate or bit depth?

Yes, exactly.

**Comment by fiso64** [comment]
I have added it in the latest version
https://github.com/fiso64/slsk-batchdl/releases/tag/v2.1

**Comment by poeti8** [comment]
Sweet, it works like a charm.

**Comment by fiso64** [comment]
Because I suspect that most people aren't aware that this will also make it ignore files where the actual bitrate may be within the set bounds, but is not known because the peer is using a particular client. That would be unexpected behavior. But this is also unexpected behavior so I'll consider it.

**Comment by fiso64** [comment]
I have updated the readme to make it clear
