### ISSUE TITLE
yt-dlp files missing from m3u on first pass of a playlist

### ISSUE THREAD

**Issue by myheartwentok** [fiso64/slsk-batchdl#28]
for some reason files downloaded from yt-dlp are not added to an m3u using --m3u all on the first time downloading a playlist, with empty lines in the m3u where they should be. If i request to download it again even though its already been downloaded, the yt-dlp files are recognised and added to the m3u. 

thanks for your hard work!

**Comment by fiso64** [comment]
I have updated the latest release with a fix https://github.com/fiso64/slsk-batchdl/releases/tag/v2.1
