### ISSUE TITLE
no option to use custom yt-dlp config or specificy yt-dlp options

### ISSUE THREAD

**Issue by minyatex** [fiso64/slsk-batchdl#30]
there is no option to use custom yt-dlp config or specificy yt-dlp options, which is quite limiting.

also i dont find the yt-dlp options chosen to be useable. at least use these, considering the aim is to download music
--embed-thumbnail
--embed-metadata
and improve the title formatting, e.g.
-o "%(title)s - %(channel)s.%(ext)s"

if this is fixed soon I will donate :)

**Comment by fiso64** [comment]
It's undocumented but there is `--yt-dlp-argument`. 

See https://github.com/fiso64/slsk-batchdl/blob/e4505a53c72098120b2626844f537cb96c8085ec/slsk-batchdl/YouTube.cs#L479-L483

If you put `{id}` and `{savepath-noext}` into the command template they will be substituted with the according values
