### ISSUE TITLE
[REQUEST] I wrote a web ui for slsk-batchdl. Can I distribute slsk-batchdl in a docker image?

### ISSUE THREAD

**Issue by outtieTV** [fiso64/slsk-batchdl#33]
I wrote a horrible web user interface for slsk-batchdl. Would you be interested in it? Also, may I distribute slsk-batchdl release in my dockerfile?

It looks like this: [https://i.imgur.com/tGDBNtJ.png](https://i.imgur.com/tGDBNtJ.png)

**Comment by fiso64** [comment]
yeah do whatever you want, project is licensed under https://en.wikipedia.org/wiki/WTFPL I guess

**Comment by markst** [comment]
Curious to know how this is going @outtieTV 
I also wondered about building a web guy which may have an audio player integrated. 
There is also this interface for Soulseek: https://github.com/slskd/slskd

**Comment by markst** [comment]
Perhaps a a web interface is a better choice. @fiso64 I had wondered about putting together a gui using a .net ui framework such as [Avalonia](https://github.com/AvaloniaUI/Avalonia)

**Comment by fiso64** [comment]
@markst I've heard about Avalonia before. Looks good, although I have no experience with it (or gui programming in general, for that matter).

I don't have much interest in working a gui wrapper myself however. I designed the cli to be convenient for me, and for my use case (which is really just downloading albums nowadays, i.e `sldl "albumname" -at`) I don't feel like I need a gui. 

Feel free to open issues or pull requests for code that would make it easier to create a gui though (if you want).

**Comment by fiso64** [comment]
Maybe it could be combined with an online music database to make an app where you can browse artists and albums from musicbrainz or discogs and which downloads the files from soulseek. That actually sounds useful

**Comment by markst** [comment]
> Maybe it could be combined with an online music database to make an app where you can browse artists and albums from musicbrainz or discogs and which downloads the files from soulseek. That actually sounds useful

@fiso64 yeah that's exactly an idea that's being conceived. Will try put some time into it and see how I go.

**Comment by outtieTV** [comment]
> Curious to know how this is going [@outtieTV](https://github.com/outtieTV) I also wondered about building a web gui which may have an audio player integrated.
> 
> There is also this interface for Soulseek: https://github.com/slskd/slskd I suppose it could somehow be integrated?

My attempt at making the webui is very messy and buggy. I'm using it only for personal use at the moment. Would love to see something official, though. Glad more people are interested in this!
