### ISSUE TITLE
Sourcing track data from file tags can lead to duplicates and inconsistencies

### ISSUE THREAD

**Issue by bakkerjoeri** [fiso64/slsk-batchdl#35]
When I download the same playlist twice with `--skip-duplicates` slight variations in spelling seem to cause the file to be downloaded again anyway, causing duplicates.

For example I have this case with a missing accent:

- Eric Prydz - Generate (Kolsch Remix).mp3
- Eric Prydz - Generate (Kölsch Remix).mp3

or this one with case problems:

- Fred again.. - Danielle (Smile on My Face).mp3
- Fred Again.. - Danielle (Smile on My Face).mp3

Because the name formatter (https://github.com/fiso64/slsk-batchdl/blob/master/slsk-batchdl/Program.cs#L3490) seems to only use the file's embedded tags to figure out track information it depends on the tags the uploader has put there, which can cause variations and lead to duplicate downloads because of these.

Another side effect of this is that untagged files are unable to produce well formatted names.

One approach to solve this I think could work here is to here https://github.com/fiso64/slsk-batchdl/blob/master/slsk-batchdl/Program.cs#L3551 first use track information sourced from Spotify to populate these values, and to then fall back to file tags if they're not present. 

This way the tags will be more consistent and more consistently present, leading hopefully to less duplicates and more data for formatting.

**Comment by fiso64** [comment]
Are you using the default check mode `name-precise`? The duplicate check should ignore case, maybe there is some file condition that is not satisfied by the existing file? I'll make it ignore diacritics as well. 

As for the source of the track information, I could add additional variables like {source-artist} and the like, but the problem is that the program does not always download the correct files. So it would end up renaming the incorrect file it downloaded to the song you actually want, and that would cause confusion.

**Comment by fiso64** [comment]
I have added {sartist}, {salbum} and {stitle} in the new version https://github.com/fiso64/slsk-batchdl/releases/tag/v2.2.2

**Comment by bakkerjoeri** [comment]
> Are you using the default check mode `name-precise`?

I am, so then maybe the case was a fluke of some other kind? Diacritics I can confirm are consistently ignored, as is the occasional symbol (a dangling `?` for example).

> but the problem is that the program does not always download the correct files

That makes sense! Thanks for explaining.

**Comment by bakkerjoeri** [comment]
> I have added {sartist}, {salbum} and {stitle} in the new version

Oh this is brilliant, thank you! Great solution, I think with that this can be closed as far as I'm concerned.
