### ISSUE TITLE
Input is already set to 'flase'

### ISSUE THREAD

**Issue by MCMXD** [fiso64/slsk-batchdl#36]
System.ArgumentException: Invalid argument 'https://open.spotify.com/playlist/....'. Input is already set to 'flase'

Doesn't matter what playlist I use, same error. Any idea what's going wrong?

Has worked well previously ..

**Comment by fiso64** [comment]
What's your full argument + config (if you're using it)

**Comment by fiso64** [comment]
By the way it seems that you wrote 'flase' where it should probably be 'false'

**Comment by MCMXD** [comment]
Sorted - had no idea what it was talking about - lucky typo. This is so epic, and you getting back so fast is insane. Thank you!

**Comment by MCMXD** [comment]
Sorted - had no idea what it was talking about - lucky typo. This is so epic, and you getting back so fast is insane. Thank you!

**Comment by MCMXD** [comment]
Sorted - had no idea what it was talking about - lucky typo. This is so epic, and you getting back so fast is insane. Thank you!
