### ISSUE TITLE
A title with a slash in it creates a folder

### ISSUE THREAD

**Issue by bakkerjoeri** [fiso64/slsk-batchdl#38]
When a track's title (perhaps also any other tag) contains a `/` character it is treated as a path separator and a folder is created. The slash character within tags used for formatting should be escaped and printed as is.

For example, when downloading for `Beyoncé - PURE/HONEY` the track was saved as as a folder with one file in it:

```
📂 Beyoncé - PURE/
   🎵 HONEY.mp3
```

**Comment by fiso64** [comment]
Thanks, should be fixed in the latest release.
