### ISSUE TITLE
Unhandled exception. System.TimeoutException: The wait timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by tasteeins** [fiso64/slsk-batchdl#4]
I LOVE your App!

Im getting a lot of this:

It starts to load the spotify songs and then -

Unhandled exception. System.TimeoutException: The wait timed out after 5000 milliseconds
   at Soulseek.SoulseekClient.ConnectInternalAsync(String address, IPEndPoint ipEndPoint, String username, String password, CancellationToken cancellationToken)
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)

Am i writing something wrong?

C:\slsk-batchdl.exe --username xx --password xy--spotify https://open.spotify.com/playlist/zzz --path C:\Soulseek --pref-format flac --skip-existing --concurrent-processes 5

LOVE YOU!

**Comment by crazyserb** [comment]
I am getting this exact same error as well.

Any idea why/what's going on? And how to get around it?
