### ISSUE TITLE
Building executable on Linux 

### ISSUE THREAD

**Issue by MCMXD** [fiso64/slsk-batchdl#41]
I understand this is a general question beyond the scope of the app.

I have been using this on Win11 and THANK YOU. I can't even find half of the tracks this baby finds when I manually search slsk. It's slowly fleshing out my new Logitech Media Server home streaming set-up with modern bangers ;)

I really want to move it over to my HoemLab so I can cron it and have it sweep periodically not just when my PC is on and I think to fire it up. 

I dont have the Linux experience, and just need a point in the right direction. I'm downloading the slsk-batchdl_linux-x64. How do you go about compiling the executable on ubuntu? Even a guide on 'a hello world project' in the same language would be swell.

If i could use VS it would be easier but im happy mashing away at the CLI until i get it. 

many thanks

**Comment by fiso64** [comment]
Just run publish.bat. If on arm64 then replace all occurrences of linux-x64 with linux-arm64 first. 
You can build it on linux with the publish.sh script too if you replace osx-arm64 with linux-x64 or linux-arm64

**Comment by MCMXD** [comment]
Worked brilliantly thanks very much!

Another quick question.
I can download spot playlists
However spot-likes throws this error

_Error: no DISPLAY environment variable specified_


__
**CLI**: sldl spotify-likes -s --display double --debug -c sldl.conf

**conf**
display="double"
username="*************"
password="*************"
pref-format="mp3"
name-format="{artist( - )title|filename}"  
path="/mnt/data/music/half-way/slsk-batchdl/" 
spotify-id="********" 
spotify-secret="*********" 
m3u="all"
listen-port="50001"

**Comment by MCMXD** [comment]
Worked it out thank you very much! A cron of this is going to be wild. Not running headless, well I can ProxMox over and sorted it out. 

For future's, I needed. 

export DISPLAY=:0
