### ISSUE TITLE
Download failed `m3u` tracks

### ISSUE THREAD

**Issue by markst** [fiso64/slsk-batchdl#44]
When performing a batch download occasionally some downloads fail.

We do have the option to pass `--m3u fails` which will keep track of failed downloads. 

This subsequently can be used for future downloads to ignore: ` --skip-not-found`

We can pass `--skip-existing` which will make best attempt at identifying if a track has already downloaded. However sometimes we experience duplication when this match is not 100%.

It would be great to be able to just pass the m3u (or a csv) of the failed downloads in order to attempt downloading again. 
Rather than passing entire playlist again which can result in duplication.

**Comment by fiso64** [comment]
I'll add `--skip-mode m3u-empty` which instead of looking at the files in the output directory will skip everything that doesn't have a failed entry in the output m3u.
Also `--skip-mode m3u` which will work similarly but only skip the tracks that have a non-failed entry in the m3u (this makes more sense when using `--m3u all`).

**Comment by fiso64** [comment]
Note that `--remove-from-source` will edit the source csv file and remove all lines where the track has been downloaded successfully. The resulting csv will only contain failed downloads and you could then run the program again with this csv. This already does what you want, I think.

**Comment by fiso64** [comment]
`--skip-mode m3u` is available in the latest release https://github.com/fiso64/slsk-batchdl/releases/tag/v2.2.7

**Comment by markst** [comment]
Incredible! thanks so much @fiso64. will give it a whirl
