### ISSUE TITLE
[Request] Adding a --track-version parameter

### ISSUE THREAD

**Issue by djcerbero** [fiso64/slsk-batchdl#45]
Hey, 
thanks for your batch dl, very cool! 

Would be fantastic to have an option to add a specific version for every research on a track or playlist such as 
--track-version <extended/radio/mashup/etc>

 For example, I'm interested in adding the word "extended" to every track on Spotify playlist (often those versions are not included in Spotify), but also would be interesting for "Radio" or "Mashup" etc for variations. 

 
 Thanks!

**Comment by fiso64** [comment]
I have updated the latest release https://github.com/fiso64/slsk-batchdl/releases/tag/v2.2.7

you can now apply the regex pattern to a specific field (title/artist/album). For instance `--regex "T:$; Extended"` will append 'Extended' to all track titles.

**Comment by djcerbero** [comment]
Cheers!
