### ISSUE TITLE
.exe file refuses to run on Windows 11

### ISSUE THREAD

**Issue by TvHead9752** [fiso64/slsk-batchdl#46]
I downloaded both versions of the .exe files for windows, and Windows tells me it "protected my PC", because it thinks its a virus. So, I tapped "run anyway". The window opens for half a second and closes itself. Is there something I'm doing wrong? I've also installed NET, if that isolates certain issues.

**Comment by fiso64** [comment]
It's a cli program.

**Comment by TvHead9752** [comment]
I see, thanks for clearing that up.On Jul 14, 2024, at 2:25 AM, fiso64 ***@***.***> wrote:﻿
It's a cli program.
