### ISSUE TITLE
Can only run the app 1x before reboot is required

### ISSUE THREAD

**Issue by MeshDigital** [fiso64/slsk-batchdl#48]
hello
When i try a 2nd playlist i get the following error.
Only when i restart my pc it works again.

Microsoft Windows [Version 10.0.22631.3958]
(c) Microsoft Corporation. All rights reserved.

C:\Users\quint>cd C:\tmp\SOULSEEKDOWNLOADER

C:\tmp\SOULSEEKDOWNLOADER>sldl "enei.csv"
Windows: Recommended to use the default command prompt to avoid printing issues.
Using columns: artist:"Artist", album:"Album", title:"Song".
Unhandled exception. Soulseek.ListenException: Failed to start listening on 0.0.0.0:50000; the IP and/or port may be in use or are otherwise unavailable
   at Soulseek.SoulseekClient.ConnectAsync(String address, Int32 port, String username, String password, Nullable`1 cancellationToken)
   at Soulseek.SoulseekClient.ConnectAsync(String username, String password, Nullable`1 cancellationToken)
   at Program.Login(Boolean random, Int32 tries)
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)

C:\tmp\SOULSEEKDOWNLOADER>

**Comment by MeshDigital** [comment]
sorry my bad.

> https://github.com/fiso64/slsk-batchdl/issues/13#issuecomment-1854144963

Apparently RekordBox uses 500000 and if the app is open you cannot use SLDL.

ideally some solution is implemented for this :)

**Comment by fiso64** [comment]
You can change the port with `--listen-port <port>`

**Comment by MeshDigital** [comment]
thanks for that reply, will use.
You are the MVP, the man, THE LEGEND.
