### ISSUE TITLE
argument --title-col is not implemented

### ISSUE THREAD

**Issue by naldir** [fiso64/slsk-batchdl#57]
Unknown argument: --title-col

you need to add at least this to Config.cs :

public string titleCol = "";

case "--tc":
case "--title-col":
	titleCol = args[++i];
	break;

not sure if it needs something else

**Comment by fiso64** [comment]
Oh, it was `--track-col` in the parsing code but `--title-col` in the manual. I updated it, you can build it yourself now (or just use `--track-col`)
