### ISSUE TITLE
Path is empty error

### ISSUE THREAD

**Issue by joranr** [fiso64/slsk-batchdl#58]
First of all, really appreciate what you have built! Is there a place when I can make a donation once I get it working?

I'm using windows and running: sldl http://spotify.com/playlist/theidofmyplayslistwhichispublic --user myusername --pass mypassword --path C:\users\Joran\Downloads

It says " loading Spotify playlist" but then afterwards I keep getting the following error:

Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path)
at system.IO.Path.GetFullPath(String path)
at Config.PostProcessArgs()
at Program.Main(String[] args)
at Program.<Main>(String[] args)

Any help would be really welcome! Thank you :)

**Comment by aleksoo** [comment]
Experiencing the same with 2.3.1 on windows, older version work without problem.

**Comment by fiso64** [comment]
sorry, I forgot to test it properly. https://github.com/fiso64/slsk-batchdl/releases/tag/v2.3.2
