### ISSUE TITLE
--on-complete (end)

### ISSUE THREAD

**Issue by WB2024** [fiso64/slsk-batchdl#61]
What would be the argument for --on-complete that terminates? 

so after it has completed the download it terminates the process?

**Comment by fiso64** [comment]
You can use any shell commands from your OS. On windows it would be `taskkill /IM sldl.exe`

**Comment by WB2024** [comment]
thank you so much for your fast reply, do you know what it would be on linux?

**Comment by fiso64** [comment]
Please use google for that.
