### ISSUE TITLE
Request - Shazam

### ISSUE THREAD

**Issue by theantnest** [fiso64/slsk-batchdl#62]
It would be amazing if there was some way to download tracks from my Shazam list.

Don't even know if that is possible, but it would be a great feature.

**Comment by outinim** [comment]
Hi, you have an auto-sync between Shazam and Spotify (it update a playlist). Just need to trigger `sldl` using your playlist from Spotify and you're good to go !
Cheers

**Comment by fiso64** [comment]
No plans for this

**Comment by markst** [comment]
@theantnest depending on what device you use to shazam, it could be pretty complicated. since I use iOS and my Shazam is synced with iCloud, I had to make a backup of my phone to extract the sqlite database. From there you can export the sql to csv and use sldl to download the playlist.
